Include utxo with datum and script in utxo selection
Python-Cardano/pycardano pull request #222
Opened 2023-04-22 20:30 UTC by cffls

A utxo with datum and script attached isn't necessarily unspentable.

2023-04-22 21:34 UTC, nielstron requested changes

2023-04-22 21:34 UTC, nielstron commented on pycardano/txbuilder.py
> +                        and not utxo.output.datum_hash  # UTxO with datum hash should be added by using
Why are you keeping the hash check but removing datum and script?

2023-04-22 21:35 UTC, nielstron commented on pycardano/txbuilder.py
> +                        and not utxo.output.datum_hash  # UTxO with datum hash should be added by using
If the spending address is not a script, there is no need to provide the original datum to spend the UTxO :)

2023-04-22 21:35 UTC, nielstron commented on pycardano/txbuilder.py
> +                        and not utxo.output.datum_hash  # UTxO with datum hash should be added by using
```suggestion
```

2023-04-23 01:37 UTC, cffls commented on pycardano/txbuilder.py
> +                        and not utxo.output.datum_hash  # UTxO with datum hash should be added by using
When a `datum_hash` is attached to a UTxO, it means that we only know the datum hash, but not the actual datum. In fact, we could only post datum hash before Vasil hardfork. To spend UTxOs with datum hash only, we need to provide the actual datum as part of the transaction. If we don't filter out these UTxOs, we can possibly build a tx that will never pass onchain validation.

2023-04-23 07:41 UTC, nielstron commented on pycardano/txbuilder.py
> +                        and not utxo.output.datum_hash  # UTxO with datum hash should be added by using
Thats not correct. Try it yourself :)

2023-04-23 17:41 UTC, cffls commented on pycardano/txbuilder.py
> +                        and not utxo.output.datum_hash  # UTxO with datum hash should be added by using
Yeah I think you are right. Datum is only required in phase 2 validation. If the address is not a script, datum doesn't matter. Thanks for correcting me.

2023-04-24 00:00 UTC, merged