Cardano cli chain context
Python-Cardano/pycardano pull request #274
Opened 2023-10-08 00:23 UTC by KINGH242

2023-10-14 21:05 UTC, cffls commented
Thanks, this is great! Looks good overall. I think it needs some integration test with cardano-cli, we can add the tests to [here](https://github.com/Python-Cardano/pycardano/tree/main/integration-test).

2023-10-30 13:17 UTC, nielstron requested changes
I did some formatting - make sure to run `make qa` to ensure that QA tests pass for your code. Formatting can be simply done with `black .`

2023-10-30 13:17 UTC, nielstron commented on pycardano/backend/cardano_cli.py
> +            ["query", "utxo", "--address", address] + self._network.value
I would recommend using `--out-file /dev/stdout` (or a temporary file path) as an additional parameter. It will return the output in neat JSON :)

2023-10-30 13:17 UTC, nielstron commented on pycardano/backend/cardano_cli.py
> +                [utxo_dict["tx_hash"], int(utxo_dict["tx_ix"])]
This throws some typecheck issues - not sure what would be the correct way of handling them since `from_primitive` is pretty weirdly typed.

2023-10-30 13:21 UTC, nielstron commented on pycardano/backend/cardano_cli.py
> +            self._mode = Mode.ONLINE
This _mode field appears unused - is there any use to having an offline mode? The CLI is only used to fetch data from a node socket or submit txs through it / these methods don't check whether the mode is offline or not

2023-10-30 13:22 UTC, nielstron commented on pycardano/backend/cardano_cli.py
> +    def _fraction_parser(fraction: str) -> float:
This function appears unused. Should it be removed?

2023-10-30 13:28 UTC, nielstron commented on pycardano/backend/cardano_cli.py
> +                "lovelaces": int(vals[2]),
This does not handle the presence of native tokens. Example:
```
fffe5a651c942ea5389439a83621dea5a02c842cfaf078f20ded03f5b70681cb     0        2650000 lovelace + 100 4fd6d8b1eac12b029cd68acd25220c20dd13b9c4b0d0b585d49135d3.53414354 + TxOutDatumHash ScriptDataInBabbageEra "2c2509a89e6a759fde1877e0f064f99395cc88596438a1a08c22d41e161dd748"
```

2023-10-30 13:32 UTC, nielstron commented on pycardano/backend/cardano_cli.py
> +            for i in extra:
Note there are also inline datums, which will look like this
```
fbaa018740241abb935240051134914389c3f94647d8bd6c30cb32d3fdb799bf     0        708864940 lovelace + 1 2e11e7313e00ccd086cfc4f1c3ebed4962d31b481b6a153c23601c0f.636861726c69335f6164615f6e6674 + 1367726755 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a.434841524c4933 + 9223372035870126880 d8d46a3e430fab5dc8c5a0a7fc82abbf4339a89034a8c804bb7e6012.636861726c69335f6164615f6c71 + TxOutDatumInline ReferenceTxInsScriptsInlineDatumsInBabbageEra (ScriptDataConstructor 0 [ScriptDataConstructor 0 [ScriptDataBytes ".\DC1\231\&1>\NUL\204\208\134\207\196\241\195\235\237Ib\211\ESCH\ESCj\NAK<#`\FS\SI",ScriptDataBytes "charli3_ada_nft"],ScriptDataConstructor 0 [ScriptDataBytes "",ScriptDataBytes ""],ScriptDataConstructor 0 [ScriptDataBytes "\142Q9\137\EOT\165\211\252\DC2\159\191O\NAK\137p\GS\226<x$\213\201\SI\219\148\144\225Z",ScriptDataBytes "CHARLI3"],ScriptDataConstructor 0 [ScriptDataBytes "\216\212j>C\SI\171]\200\197\160\167\252\130\171\191C9\168\144\&4\168\200\EOT\187~`\DC2",ScriptDataBytes "charli3_ada_lq"],ScriptDataNumber 997,ScriptDataList [ScriptDataBytes "M\217\138.\243K\199\172\&8X\187\207\223\148\170\161\SYN\187(\202~\SOHua@\186M\EM"],ScriptDataNumber 10000000000])
```

respectively in JSON
```json
{
    "fbaa018740241abb935240051134914389c3f94647d8bd6c30cb32d3fdb799bf#0": {
        "address": "addr1x8nz307k3sr60gu0e47cmajssy4fmld7u493a4xztjrll0aj764lvrxdayh2ux30fl0ktuh27csgmpevdu89jlxppvrswgxsta",
        "datum": null,
        "inlineDatum": {
            "constructor": 0,
            "fields": [
                {
                    "constructor": 0,
                    "fields": [
                        {
                            "bytes": "2e11e7313e00ccd086cfc4f1c3ebed4962d31b481b6a153c23601c0f"
                        },
                        {
                            "bytes": "636861726c69335f6164615f6e6674"
                        }
                    ]
                },
                {
                    "constructor": 0,
                    "fields": [
                        {
                            "bytes": ""
                        },
                        {
                            "bytes": ""
                        }
                    ]
                },
                {
                    "constructor": 0,
                    "fields": [
                        {
                            "bytes": "8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a"
                        },
                        {
                            "bytes": "434841524c4933"
                        }
                    ]
                },
                {
                    "constructor": 0,
                    "fields": [
                        {
                            "bytes": "d8d46a3e430fab5dc8c5a0a7fc82abbf4339a89034a8c804bb7e6012"
                        },
                        {
                            "bytes": "636861726c69335f6164615f6c71"
                        }
                    ]
                },
                {
                    "int": 997
                },
                {
                    "list": [
                        {
                            "bytes": "4dd98a2ef34bc7ac3858bbcfdf94aaa116bb28ca7e01756140ba4d19"
                        }
                    ]
                },
                {
                    "int": 10000000000
                }
            ]
        },
        "inlineDatumhash": "c56003cba9cfcf2f73cf6a5f4d6354d03c281bcd2bbd7a873d7475faa10a7123",
        "referenceScript": null,
        "value": {
            "2e11e7313e00ccd086cfc4f1c3ebed4962d31b481b6a153c23601c0f": {
                "636861726c69335f6164615f6e6674": 1
            },
            "8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a": {
                "434841524c4933": 1367726755
            },
            "d8d46a3e430fab5dc8c5a0a7fc82abbf4339a89034a8c804bb7e6012": {
                "636861726c69335f6164615f6c71": 9223372035870126880
            },
            "lovelace": 708864940
        }
    }
}
```

2023-11-01 21:16 UTC, KINGH242 commented
Thanks for the review and feedback. I will work on the fixes over the coming week.

2023-11-02 17:01 UTC, KINGH242 commented on pycardano/backend/cardano_cli.py
> +            ["query", "utxo", "--address", address] + self._network.value
I have refactored to use `--out-file /dev/stdout`. This also solves some of the other issues around parsing the UTxO data.
https://github.com/KINGH242/pycardano/commit/20b544f4f0f29e1471568b05fa343abe4f5220da

2023-11-02 17:10 UTC, KINGH242 commented on pycardano/backend/cardano_cli.py
> +                [utxo_dict["tx_hash"], int(utxo_dict["tx_ix"])]
This issue has gone away since refactoring. The transaction hash and index now come from a string value.

2023-11-02 17:12 UTC, KINGH242 commented on pycardano/backend/cardano_cli.py
> +            self._mode = Mode.ONLINE
The unused mode code has been removed.
https://github.com/KINGH242/pycardano/commit/efe16980a58670ac6fbffdc188ca34b0dd5cdc03

2023-11-02 17:13 UTC, KINGH242 commented on pycardano/backend/cardano_cli.py
> +    def _fraction_parser(fraction: str) -> float:
The unused fraction parser code has been removed.
https://github.com/Python-Cardano/pycardano/pull/274/commits/6ae4e642b12ab2195ba436573126232f17b1d9df

2023-11-02 17:15 UTC, KINGH242 commented on pycardano/backend/cardano_cli.py
> +                "lovelaces": int(vals[2]),
The `_utxos` method refactor addresses this.

2023-11-02 17:17 UTC, KINGH242 commented on pycardano/backend/cardano_cli.py
> +            for i in extra:
The `_utxos` method refactor addresses this as well, but it may need another look to ensure that all various scenarios are handled.

2023-11-02 17:49 UTC, KINGH242 commented
> Thanks, this is great! Looks good overall. I think it needs some integration test with cardano-cli, we can add the tests to [here](https://github.com/Python-Cardano/pycardano/tree/main/integration-test).

I will work on adding integration tests for the cardano-cli chain context next. But to do so, I will need to add the [Docker SDK for Python](https://docker-py.readthedocs.io/en/stable/#) package. This will be an improvement to the cardano-cli chain context that would allow the user to use PyCardano with the cardano-cli in a Docker container.

2023-11-03 10:23 UTC, nielstron commented
@KINGH242 the PyCardano already contains integrations tests, which are run in a docker container with Ogmios (and likely also the cardano CLI accessible) - I think the Ogmios endpoint is also tested there.

Just pointing you in case you were not aware :)
https://github.com/Python-Cardano/pycardano/tree/main/integration-test

2023-11-03 16:39 UTC, cffls commented
> likely also the cardano CLI accessible

This is correct. `cardano-cli` is runnable in the docker container. [This](https://github.com/Python-Cardano/pycardano/blob/main/integration-test/run_pool.sh#L15) is an example where a transaction is created from cardano-cli.

2024-01-01 17:51 UTC, cffls commented
Looks good to me. Added more integration tests. I noticed that `evaluate_tx_cbor` is not implemented in `CardanoCliChainContext`. Is it because cardano-cli is not able to evaluate a tx?

2024-01-01 21:14 UTC, KINGH242 commented
I just realized that this can be done using ‘transaction build ... --calculate-plutus-script-cost’. Never saw or used it before. I will implement it this week.

2024-01-10 10:04 UTC, nielstron approved these changes

2024-02-06 08:37 UTC, nielstron commented
> I just realized that this can be done using ‘transaction build ... --calculate-plutus-script-cost’. Never saw or used it before. I will implement it this week.

I just realized that going through the calculate-plutus-script-cost is quite painful because we would need to essentially disassemble the transaction for the cli to re-build it. I think this is fine to be merged as-is and a cost estimation can be added later based on a per-demand basis.

Moreover, uplc 1.0.0 could be used to estimate script cost now entirely without the need of any backend so the estimation based on cli or ogmios or blockfrost might become unneccessary.

2024-02-06 08:37 UTC, merged

2024-02-06 16:18 UTC, cffls commented
Awesome! It would be great if we can get rid of the dependency on chain context for fee estimation.