Add path to Ogmios v6 backend
Python-Cardano/pycardano pull request #398
Opened 2024-11-16 18:19 UTC by theeldermillenial

A couple of months ago, I added a `path` argument to Ogmios.

https://gitlab.com/viperscience/ogmios-python/-/merge_requests/13

This PR adds support for the `path` argument in the Ogmios chain context.

2024-11-16 18:23 UTC, nielstron requested changes
looks good overall, but I think an unintended change snuck in

2024-11-16 18:23 UTC, nielstron commented on pycardano/backend/ogmios_v6.py
> +            if script["language"] == "plutus:v2":
this should probably not be here

2024-11-16 19:12 UTC, theeldermillenial commented on pycardano/backend/ogmios_v6.py
> +            if script["language"] == "plutus:v2":
It sure did, I'll fix it.

2024-12-07 15:44 UTC, cffls commented
LGTM, pushed a minor fix.

2024-12-09 19:48 UTC, nielstron approved these changes

2025-01-10 17:55 UTC, merged